version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: okestro2713
      MYSQL_DATABASE: omok
      MYSQL_USER: okestro
      MYSQL_PASSWORD: okestro2713
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: